name: Automate run tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Upgrade pip install
      run: pip install --upgrade pip
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      env:
        LOGIN: ${{ secrets.LOGIN }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: pytest
